language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - SYMFONY_VERSION=symfony-1.4.20

before_script:
    - ./prepare_tests.sh

script: php mockproject/plugins/sfPropelORMPlugin/test/bin/prove.php
