language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

env:
    - SYMFONY_BRANCH=propel SYMFONY_REPOSITORY=https://github.com/rozwell/symfony1.git

before_script:
    - ./prepare_tests.sh

script: php mockproject/plugins/sfPropelORMPlugin/test/bin/prove.php
