<?php



/**
 * Skeleton subclass for representing a row from the 'toy_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1 on:
 *
 * 08/29/11 10:59:26
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ToyI18n extends BaseToyI18n {

} // ToyI18n
