<?php



/**
 * Skeleton subclass for performing query and update operations on the 'toy_propel_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1 on:
 *
 * 09/09/11 18:01:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ToyPropelI18nPeer extends BaseToyPropelI18nPeer {

} // ToyPropelI18nPeer
